force-app/main/default/objects/Suma__c/Suma__c.object-meta.xml
<CustomObject>
    <label>Suma</label>
    <nameField>
        <label>Suma Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sumas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suma__c/fields/resultado__c.field-meta.xml
<CustomField>
    <fullName>resultado__c</fullName>
    <label>resultado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suma__c/fields/Valor_Dos__c.field-meta.xml
<CustomField>
    <fullName>Valor_Dos__c</fullName>
    <label>Valor Dos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suma__c/fields/Valor_Uno__c.field-meta.xml
<CustomField>
    <fullName>Valor_Uno__c</fullName>
    <label>Valor Uno</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/classumasingl.cls
public with sharing class classumasingl { //nombre de la clase sintaxis
    
    private List<suma__c> lista = new list<suma__c>();
    
    private static classumasingl instance = null;
    
    private classumasingl (List<suma__c>lista){
        this.lista = lista;
    }
    public static classumasingl getInstance(List<suma__c> lista)
    {
       if(instance == null){
           instance = new classumasingl(lista);
       }
       return instance;
   }
   private void sumarTrigg(){
       for(Integer i = 0; i < this.lista.size(); i ++){

           this.lista[i].resultado__c = this.lista[i].Valor_Dos__c + this.lista[i].Valor_Uno__c;
       }
   }
   public void getSuma(){

       sumarTrigg();
   }
}