force-app/main/default/objects/Suma__c/Suma__c.object-meta.xml
<CustomObject>
    <label>Suma</label>
    <nameField>
        <label>Suma Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sumas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suma__c/fields/n1__c.field-meta.xml
<CustomField>
    <fullName>n1__c</fullName>
    <label>n1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suma__c/fields/n2__c.field-meta.xml
<CustomField>
    <fullName>n2__c</fullName>
    <label>n2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Sumar_tst.cls
@isTest
public with sharing class Sumar_tst {
    public Sumar_tst() {
    }
    @TestSetup
    static void makeData(){
        List<Suma__c> lista = new List<Suma__c>();
        for(integer i = 0; i < 200; i++){
            lista.add(new Suma__c(n1__c=i, n2__c=i+1));
        }
        System.debug(lista);
        Database.insert(lista);
    }
    static testmethod void testSuma(){
        List<Suma__c> newLista = Database.query('select n1__c, n2__c from Suma__c');
        Sumar.getInstance(newLista).getSuma();
    }
}