force-app/main/default/objects/Suma__c/Suma__c.object-meta.xml
<CustomObject>
    <label>Suma</label>
    <nameField>
        <label>Suma Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sumas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suma__c/fields/n1__c.field-meta.xml
<CustomField>
    <fullName>n1__c</fullName>
    <label>n1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suma__c/fields/n2__c.field-meta.xml
<CustomField>
    <fullName>n2__c</fullName>
    <label>n2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suma__c/fields/resultado__c.field-meta.xml
<CustomField>
    <fullName>resultado__c</fullName>
    <label>resultado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Sumar.cls
public with sharing class Sumar {
    private  List<Suma__c> lista = new List<Suma__c>();
  
    private static  Sumar instance  = null;    
    private Sumar(List<Suma__c>lista) {
        this.lista = lista;  
    }  
    public static Sumar getInstance(List<Suma__c>lista){
  
      if(instance  == null){
        instance = new Sumar(lista);
      }
      return instance;
    }
  
    private  void sumarTrigg(){  
      for (Integer i = 0; i < this.lista.size(); i++) { 
          this.lista[i].Resultado__c =  this.lista[i].n1__c +  this.lista[i].n2__c;
        }
   }
  
  public void getSuma(){
       sumarTrigg();
    }  
  }