force-app/main/default/objects/Cancion__c/Cancion__c.object-meta.xml
<CustomObject>
    <label>Cancion</label>
    <nameField>
        <displayFormat>CAN-{0000}</displayFormat>
        <label>Cancion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancion__c/fields/Cancion__c.field-meta.xml
<CustomField>
    <fullName>Cancion__c</fullName>
    <label>Cancion</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cancion__c/fields/Letra__c.field-meta.xml
<CustomField>
    <fullName>Letra__c</fullName>
    <label>Letra</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/songs.cls
public class songs {
    
    @future(callout=true)
    public static void getSong(String autor, String cancion, id IdCancion)
    {
        songsC s = new songsC();
        
        Http http = new http();

        HttpRequest Request = new HttpRequest();

        Request.setEndpoint('https://api.lyrics.ovh/v1/:' +autor + '/:' +cancion);

        Request.setMethod('GET');

        HttpResponse Response = http.send(Request);

        String respuesta = Response.getBody();

        s = (songsC) JSON.deserializeStrict(respuesta, songsC.class);

        Cancion__c cancionObj = new Cancion__c(Id = IdCancion, letra__c = s.lyrics);

        update cancionObj;

    }

    public class songsC{

		  public String lyrics{get;set;}
    
    }
}